kind: Secret
apiVersion: v1
metadata:
  name: goserver-secret
type: Opaque #é o default
data:
  USER: QnJ1bm8K #Bruno em Base64
  PASSWORD: MTIzNDU2Cg== #123456 em Base64

# A vantagem desse cara aqui em relacao ao configMap, é só que não dá pra bater o olho e entender o valor !