kind: Deployment 
apiVersion: apps/v1
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "wesleywillians/hello-go:v5.1"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef: #So add essa linha
                name: goserver-secret #So add essa linha
          volumeMounts: 
            - mountPath: "/go/myfamily" 
              name: config 
              readOnly: true 
      volumes: 
        - name: config 
          configMap:
            name: configmap-family 
            items:
            - key: members 
              path: "family.txt" 
# Ao ler o conteudo da secret pelo app no container o kubernets da o valor decodado.