kind: Deployment 
apiVersion: apps/v1
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "brunomeloesilva/hello-go:v5.4"
          readinessProbe: # Responsabilidade de Tirar o trafego fora.
            httpGet:
              path: /healthz
              port: 8000 
            periodSeconds: 3 
            failureThreshold: 1 
            initialDelaySeconds: 10 
          livenessProbe: #(Responsabilidade de Recriar o processo. So ele reinicia!) ERROR: Quando o livenessProbe checa, a cada 5s, a aplicacão ainda não está pronta então ele reinicia os pods. E ficará em um looping de erro eterno devido o "initialDelaySeconds: 10" acima.
            httpGet:
              path: /healthz 
              port: 8000 
            periodSeconds: 5 
            failureThreshold: 1 
            timeoutSeconds: 1 
            successThreshold: 1 
            initialDelaySeconds: 10 #Isso aqui já resolveria o erro acima.
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts: 
            - mountPath: "/go/myfamily" 
              name: config 
              readOnly: true 
      volumes: 
        - name: config 
          configMap:
            name: configmap-family 
            items:
            - key: members 
              path: "family.txt"

# $ docker build -t brunomeloesilva/hello-go:v5.4 .
# $ docker push brunomeloesilva/hello-go:v5.4
# $ kubectl apply -f 13-deployment-to-health-readiness.yaml && watch -n1 kubectl get po
