kind: Deployment
apiVersion: apps/v1
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: 'brunomeloesilva/hello-go:v9.6'
          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 4
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            - mountPath: "/go/pvc" #Aqui
              name: goserver-volume
      volumes:
        - name: goserver-volume #Aqui
          persistentVolumeClaim:
            claimName: goserver-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt

# bs@pc:~/Documents/k8s$ kubectl apply -f 22.usando-pvc.yaml 
# deployment.apps/goserver configured

# bs@pc:~/Documents/k8s$ kubectl get pvc
# NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
# goserver-pvc   Bound    pvc-346ec1fc-18fd-4dc0-9d91-b48b3d4e98a7   5Gi        RWO            standard       <unset>                 57m

# bs@pc:~/Documents/k8s$ kubectl get pods
# NAME                        READY   STATUS    RESTARTS   AGE
# goserver-6cdf8b9754-llllx   1/1     Running   0          5m24s

# bs@pc:~/Documents/k8s$ kubectl exec -it goserver-6cdf8b9754-llllx -- bash
# root@goserver-6cdf8b9754-llllx:/go#

# root@goserver-6cdf8b9754-llllx:/go# ls *c 
# pvc: