kind: Deployment # Ao realizar alteracoes aqui, ele ja deleta todos os pods e cria os novos, resolvendo o problema do replicaSet.
apiVersion: apps/v1
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "wesleywillians/hello-go:latest" 