kind: Service
apiVersion: v1
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 80 # a porta 80 deste service esta apontando para porta 80 do container docker
    protocol: TCP
