kind: Service
apiVersion: v1
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer # Gera um IP externo para vc acessar sua aplicaćão de fora.
  ports:
  - name: goserver-service
    port: 80 # a porta 80 deste service esta apontando para porta 80 do container docker(se nao houvesse targetPort definido). O port-forward se faz com essa porta aqui, <porta-de-escola:80>.
    targetPort: 8000 # Este aqui indica a porta do container docker, util quando a porta do service é diferente da porta do container. Ou seja, Quando acessamos o o service na porta 80, ele redireciona para porta 9000 do container, e te responde na porta 80.
    protocol: TCP

# Se vc der o apply localmente ele nao vai gerar o IP externo. Só gera na Cloud..
# Gera automaticamente o nodePort aleatorio.
# É esse tipo que usamos para expor as aplicacoes para internet.